[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/bubblemaps/*"
  to = "/.netlify/functions/bubblemaps/:splat"
  status = 200

[[redirects]]
  from = "/api/beta-applications"
  to = "/.netlify/functions/beta-applications"
  status = 200

[[redirects]]
  from = "/api/beta-applications/*"
  to = "/.netlify/functions/beta-applications/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
